<?php

namespace WpClusterCache\Admin\Helpers;

class HtmlTab extends HtmlForm {

	private $tabName = '';
	private $label = '';
	private $id = '';

	public function __construct( $attr = [], $content = [] ) {

		$id = 'tab-' . rand( 0, 100 );
		if ( is_string( $attr ) ) {
			$attr = [ 'title' => $attr, 'label' => $attr ];
		}
		$attr = array_merge( [
			'title'   => $id,
			'label'   => $id,
			'id'      => $id,
			'content' => $content
		], $attr );

		$this->setId( $attr['id'] )->setLabel( $attr['label'] ?: $attr['title'] )->setTabName( $attr['title'] )->add( $attr['content'] );
//		parent::__construct( $html );
	}

	/**
	 * @return string
	 */
	public function getTabName(): string {
		return $this->tabName;
	}

	/**
	 * @param string $tabName
	 *
	 * @return HtmlTab
	 */
	public function setTabName( string $tabName ): HtmlTab {
		$this->tabName = $tabName;

		return $this;
	}

	public function __toString() {
		return $this->wrap( $this->subtitle( $this->getLabel() ) . parent::__toString(), 'div', [ 'id' => $this->getId(), 'class' => 'ui-tabs-vertical' ] ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function getLabel(): string {
		return $this->label;
	}

	/**
	 * @param string $label
	 *
	 * @return HtmlTab
	 */
	public function setLabel( string $label ): HtmlTab {
		$this->label = $label;

		return $this;
	}

	/**
	 * @return string
	 */
	public function getId(): string {
		return $this->id;
	}

	/**
	 * @param string $id
	 *
	 * @return HtmlTab
	 */
	public function setId( string $id ): HtmlTab {
		$this->id = $id;

		return $this;
	}


}