<?php

namespace WpClusterCache\Admin\Views;

use WpClusterCache\Admin\Helpers\HtmlForm;
use WpClusterCache\Settings;
use WpClusterCache\UserProfile;

class AdminForm extends HtmlForm {

	protected $_html = [];

	public function __toString() {

		return $this->form( parent::__toString() ); // TODO: Change the autogenerated stub
	}


	public function printSettings() {
		$hosts = (array) Settings::getHosts();

		return $this->table( [
			$this->textareaSetting( Settings::getConfigNameOfHosts(), 'Hosts a Conectar', isset( $hosts ) ? implode( "\n", $hosts ) : '', '' ),
			$this->inputSetting( Settings::getConfigNameOfPort(), 'Port', Settings::getPort(), '80', 'number' ),
			$this->inputSetting( Settings::getConfigNameOfProtocol(), 'Protocol', Settings::getProtocol(), 'http' ),


		], [ 'style' => 'width:60%' ] );
	}


}